version: '3.8'
services:
  django-web:
    build: .
    container_name: django-docker
    expose:
      - "8000"  # Internal port for Gunicorn, not exposed to host
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Share static files with Nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config
      - static_volume:/usr/share/nginx/html/static  # Static files
    depends_on:
      - django-web

volumes:
  static_volume:  # Named volume for static files