# Generated by Django 5.1.6 on 2025-04-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0002_alter_answer_user_alter_report_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_selections', to='grc.question')),
            ],
        ),
    ]
