# Generated by Django 5.1.6 on 2025-03-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Default Customer Name', max_length=200),
        ),
    ]
