# Generated by Django 5.1.6 on 2025-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0004_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='grc.sector'),
        ),
    ]
