# Generated by Django 5.1.6 on 2025-03-20 13:34

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0006_category_sector_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='grc.sectorcategory')),
            ],
            options={
                'verbose_name_plural': 'Sector Categories',
            },
        ),
        migrations.AlterField(
            model_name='sector',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='grc.sectorcategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
