# Generated by Django 5.1.6 on 2025-03-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0009_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
