# Generated by Django 5.1.6 on 2025-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='competitor_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='decision_support',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='governance_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='governance_topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='minimum_policy_set',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='minimum_solution_set',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='primary_risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='regulatory_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='risk_surface',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='solution_roadmap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='stakeholder_expectations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
